### ISSUE TITLE
Possible to see the site in an earlier version ?

### ISSUE THREAD

**Issue by lems3** [openeuropa/entity_version#25]
Hi!

While looking for a solution to a client request that I got, I found this repo (and the OpenEuropa project)...

I understand that this is not a complete feature request... but right now, we're looking for ideas on how to solve our issue.

Our client would like to ship documentation with their software. The issue is that their software may live in different versions at the same time. They need to have a versionned documentation to make it easier for the end users to have the right information.

Would the entity version module allows us to show to a user a site in a specific version ? We'd like to show a dropdown of versions number, and once the user select one, they get the site with content on that specific version.

We could try to hack something with taxonomy, but that would imply the creation of a lot of duplicates in content...

Since entities with revisions already have those earlier versions of content, being able to show a list of versions somewhere could make it a lot easier to maintain the site...

**Comment by ndf** [comment]
Hi @lems3, we have a very similar request from a client.

May I ask how did you solve it in the end?

**Comment by lems3** [comment]
We didn't. After a couple of test we see it was not feasible within Drupal, the client moved to a different vendor.

**Comment by nagyad** [comment]
I have completely missed this issue sorry, would have been better to see this as a "Support request" in drupal.org issue queue. :( 

As for the issue you faced, I understand you didn't manage to solve the problem, however, I leave here some thoughts for others might face such a request. 
You could make something like that, by creating a custom block containing a custom form, which gets the given content either from the route (if you are on the canonical page of the content) or some other way, and you query all the revisions of that content and populate a select list with the version numbers from the version field from each revision, depending on your setup normally each version number corresponds to a revision, and basically just submit the form to view the selected revision of the content.

**Comment by lems3** [comment]
Hi!

No worries!

As for your approach, it would work when you want to browse specific content with their own versions. We were looking for an experience closer to what you get from https://www.drush.org/12.x/ for example.

For now our understanding is that it requires a lot of custom elements to make it happen. So we opted to use a different platform that offers this out of the box.
